[package]
name = "advent-of-code-2024"
version = "0.1.0"
authors = ["Mukul Agarwal"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
rust-crypto = "0.2.36"

